### PR TITLE
Requirement of electron-packager

### PR DESCRIPTION
**Pull request by wincelau**
Add in readme requirement of electron-packager

### CODE REVIEW

**Comment by malept** [comment]
Thanks for the pull request, but Electron Packager is not a hard requirement for this module. If necessary, you can choose to [make a bundled Electron app manually](https://www.electronjs.org/docs/tutorial/application-distribution#manual-distribution).

**Comment by wincelau** [comment]
Ok it's just when apply this command in Usage Readme https://github.com/electron-userland/electron-installer-debian/blame/master/README.md#L70 i don't have elecron-packager installed. I had to look how get this package, but it's maybe because i the first time i work with electron.

Thank you for you response

**Comment by malept** [comment]
I think a better way to fix the problem would be to rewrite the Usage guide.

**Comment by wincelau** [comment]
Yes you're right done here 4961ea95c61b4ce4d07a084c8cfb299298482f74

**Pull request closed without merging**
