### PR TITLE
feat: add dependencies for Electron >= 9

### PR DESCRIPTION
**Pull request by fcastilloec**
This PR needs https://github.com/electron-userland/electron-installer-common/pull/66 to be merged first

### CODE REVIEW

**Comment by thamara** [comment]
I have bumped into one issue I believe this could solve. After upgrading electron on my app, the following error started to happen:

> 2020-06-27T04:44:17.7344963Z ##[group]Run npx electron-installer-debian --src 'release-builds/time-to-leave-linux-x64/' --dest 'packages/' --arch amd64 --verbose
2020-06-27T04:44:17.7345155Z [36;1mnpx electron-installer-debian --src 'release-builds/time-to-leave-linux-x64/' --dest 'packages/' --arch amd64 --verbose[0m
2020-06-27T04:44:17.7380803Z shell: /bin/bash -e {0}
2020-06-27T04:44:17.7380920Z ##[endgroup]
2020-06-27T04:44:21.8268078Z npx: installed 75 in 4.023s
2020-06-27T04:44:21.9362773Z Creating package (this may take a while)
2020-06-27T04:44:22.6786947Z { Error: Command failed with a non-zero return code (2):
2020-06-27T04:44:22.6788102Z fakeroot dpkg-deb --build /tmp/electron-installer--2818-9S49vIKmy97b/time-to-leave_1.5.4_amd64
2020-06-27T04:44:22.6788713Z 
2020-06-27T04:44:22.6797246Z dpkg-deb: error: parsing file '/tmp/electron-installer--2818-9S49vIKmy97b/time-to-leave_1.5.4_amd64/DEBIAN/control' near line 6 package 'time-to-leave':
2020-06-27T04:44:22.6798222Z  'Depends' field, missing package name, or garbage where package name expected
2020-06-27T04:44:22.6798950Z     at ChildProcess.process.on (/home/runner/.npm/_npx/2818/lib/node_modules/electron-installer-debian/node_modules/@malept/cross-spawn-promise/dist/src/index.js:84:24)
2020-06-27T04:44:22.6799339Z     at ChildProcess.emit (events.js:198:13)
2020-06-27T04:44:22.6799644Z     at maybeClose (internal/child_process.js:982:16)
2020-06-27T04:44:22.6799967Z     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
2020-06-27T04:44:22.6800399Z   cmd: 'fakeroot',
2020-06-27T04:44:22.6800665Z   args:
2020-06-27T04:44:22.6801039Z    [ 'dpkg-deb',
2020-06-27T04:44:22.6801461Z      '--build',
2020-06-27T04:44:22.6801971Z      '/tmp/electron-installer--2818-9S49vIKmy97b/time-to-leave_1.5.4_amd64' ],
2020-06-27T04:44:22.6802399Z   stdout: '',
2020-06-27T04:44:22.6802776Z   stderr:
2020-06-27T04:44:22.6803540Z    'dpkg-deb: error: parsing file \'/tmp/electron-installer--2818-9S49vIKmy97b/time-to-leave_1.5.4_amd64/DEBIAN/control\' near line 6 package \'time-to-leave\':\n \'Depends\' field, missing package name, or garbage where package name expected\n',
2020-06-27T04:44:22.6804878Z   code: 2 } 'Error: Command failed with a non-zero return code (2):\nfakeroot dpkg-deb --build /tmp/electron-installer--2818-9S49vIKmy97b/time-to-leave_1.5.4_amd64\n\ndpkg-deb: error: parsing file \'/tmp/electron-installer--2818-9S49vIKmy97b/time-to-leave_1.5.4_amd64/DEBIAN/control\' near line 6 package \'time-to-leave\':\n \'Depends\' field, missing package name, or garbage where package name expected\n    at ChildProcess.process.on (/home/runner/.npm/_npx/2818/lib/node_modules/electron-installer-debian/node_modules/@malept/cross-spawn-promise/dist/src/index.js:84:24)\n    at ChildProcess.emit (events.js:198:13)\n    at maybeClose (internal/child_process.js:982:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)'
2020-06-27T04:44:22.8615219Z ##[error]Process completed with exit code 1.


Is there any ETA to when this PR would be merged and released? Do you know of any workaround that does not involve downgrading electron on my app?
Thanks!

**Comment by giovannijunior** [comment]
@thamara, a workaround is replacing 

`<% } %><% if (depends && depends.length) { %>Depends: <%= depends.join(', ') %>`

with 

`<% } %><% if (depends && depends.length) { %>Depends: <%= depends.filter(d => d != undefined).join(', ') %>`

in node_modules/electron-installer-debian/resources/control.ejs

**Comment by malept** [comment]
It would help to know why that happens and if it happens in version 3.1.0.

**Comment by giovannijunior** [comment]
Version 3.1.0 solved it. Thank you!

**Comment by thamara** [comment]
Version 3.1.0 has also solved the issue I was facing. Thanks a lot!

**Pull request merged**
