### PR TITLE
添加iconName选项

### PR DESCRIPTION
**Pull request by inkroom**
解决部分操作系统下图标名称冲突导致无法正常显示图标问题（deepin下vscode存在该问题）

### CODE REVIEW

**Comment by malept** [comment]
Thanks for the pull request, but I don't think we want to take this. I think since we have the ability to set a [`desktopTemplate`](https://github.com/electron-userland/electron-installer-debian/tree/v1.0.1#optionsdesktoptemplate) file, adding yet another option to set something in the desktop file that most people don't need to set is unnecessary.

**Comment by inkroom** [comment]
Why I added the iconName option?Because the icon will show as a wrong icon in deepin os sometime.  set a desktopTemplate file can not deal the question. But I agree that the funtion is not necessary for most people, since they do not use deepin os.





------------------ 原始邮件 ------------------
发件人: "Mark Lee"<notifications@github.com>;
发送时间: 2018年12月26日(星期三) 中午1:07
收件人: "electron-userland/electron-installer-debian"<electron-installer-debian@noreply.github.com>;
抄送: "245900986"<245900986@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [electron-userland/electron-installer-debian] 添加iconName选项 (#164)




Thanks for the pull request, but I don't think we want to take this. I think since we have the ability to set a desktopTemplate file, adding yet another option to set something in the desktop file that most people don't need to set is unnecessary.

**Comment by malept** [comment]
Can you point to a website (preferably in English) that explains why this is necessary, specifically for deepin?

**Comment by inkroom** [comment]
I am sorry I can't point a English website. But I can give you some pictures, in this url  https://feedback.deepin.org/feedback/detail/22415 .To be honest , this is deepin's bug .





------------------ 原始邮件 ------------------
发件人: "Mark Lee"<notifications@github.com>;
发送时间: 2018年12月28日(星期五) 凌晨1:17
收件人: "electron-userland/electron-installer-debian"<electron-installer-debian@noreply.github.com>;
抄送: "245900986"<245900986@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [electron-userland/electron-installer-debian] 添加iconName选项 (#164)




Can you point to a website (preferably in English) that explains why this is necessary, specifically for deepin?

**Comment by malept** [comment]
I don't think we want to add a feature for the purpose of working around a (very odd) bug in a distro that was just reported. (Why would the icon change to `wallpaper`??)

**Comment by inkroom** [comment]
OK, you are right





------------------ 原始邮件 ------------------
发件人: "Mark Lee"<notifications@github.com>;
发送时间: 2018年12月28日(星期五) 中午12:43
收件人: "electron-userland/electron-installer-debian"<electron-installer-debian@noreply.github.com>;
抄送: "245900986"<245900986@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [electron-userland/electron-installer-debian] 添加iconName选项 (#164)




I don't think we want to add a feature for the purpose of working around a (very odd) bug in a distro that was just reported. (Why would the icon change to wallpaper??)

**Pull request closed without merging**
