### PR TITLE
feat: add support for non-default compression types

### LINKED ISSUE #272: Allow setting deb's compression type
On Ubuntu 21.10 (and later), the default compression type of deb packages created using `dpkg-deb` is ZStandard (previously it was XZ). 

However, Debian doesn't support installing ZStandard compressed packages:

```
dpkg -i trilium_0.48.3_amd64.deb 
dpkg-deb: error: archive 'trilium_0.48.3_amd64.deb' uses unknown compression for member 'control.tar.zst', giving up
dpkg: error processing archive trilium_0.48.3_amd64.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 trilium_0.48.3_amd64.deb
```

This means that when you use electron-installer-debian to build packages on Ubuntu 21.10 or later, these packages are unusable in debian. 

When using dpkg-deb directly it's possible to change the compression type via `-Zxz` flag but this is not exposed in electron-installer-debian configuration.

### PR DESCRIPTION
**Pull request by fcastilloec**
fixes #272

### CODE REVIEW

**Comment by yktoo** [comment]
Hi maintainers, could you please approve this? `electron-installer-debian` is currently making packages that are not installable in Debian.

**Comment by JSKitty** [comment]
Hey @malept, can you please review and merge? This has been open far too long!

**Comment by mbretter** [comment]
same here, our electron packages are unusable under debian when building on ubuntu 22.04.

**Comment by erikian** [comment]
For anyone who's looking for a workaround/alternative in the meantime, I've developed two packages to create .deb installers: [electron-deboa-maker](https://github.com/erikian/electron-deboa-maker), which is a maker for electron-forge, and [deboa](https://github.com/erikian/deboa), which is the core package (integrating it into build pipelines that don't use electron-forge should be straighforward).

They both work on Windows/Linux/macOS, no fakeroot/dpkg needed, and provide compression in tar/tar.gz/xz formats, among other features.

**Review by RouR — APPROVED** [review]

**Comment by VerteDinde** [comment]
Closed in favor of #342 - sorry, CI was stuck here and I could only get it to run on a new PR, but gave you co-author credit on the commit. Thanks for contributing this! 🙇‍♀️

**Pull request closed without merging**
